---
all:
  hosts:
    jenkins-master-01:
      ansible_host:
      ansible_host: 51.250.89.186
    jenkins-agent-01:
      ansible_host:  84.201.129.53
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos