apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
spec:
  selector:
    matchLabels:
      name: multitool
  template:
    metadata:
      labels:
        name: multitool
    spec:
      volumes:
      - name: logs
        hostPath:
          path: /var/log
      containers:
      - name: multitool
        image: wbitt/network-multitool
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort:  8080
          name: http
        - containerPort: 44333
          name: https
        volumeMounts:
        - name: logs
          mountPath: /input/
      terminationGracePeriodSeconds: 30
