apiVersion: v1
kind: Pod
metadata:
  labels:
    app: toolpod
  name: toolpod
spec:
  containers:
  - image: wbitt/network-multitool
    imagePullPolicy: Always
    name: toolpod
#    ports:
#    - containerPort: 8080
#      protocol: TCP
#    - containerPort:  8080
#      name: http
#    - containerPort: 44344
#      name: https
#    env:
#      - name: HTTP_PORT
#        value: "8888"
#      - name: HTTP_PORTS
#        value: "44344"



