---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.65.196
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: remoteuser
    ansible_ssh_private_key_file: ~/.ssh/remoteuser