---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
platforms:
  - name: centos7
#    image: quay.io/centos/centos:stream8
    image: docker.io/centos:centos7
    privileged: true
    pre_build_image: true
  - name: ubuntu latest
    image: docker.io/ubuntu:latest
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
