---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
    - name: Execute vector
      command: vector --version
      changed_when: false
      register: vector_version_rc
    - name: Check vector config
      command: vector validate
      changed_when: false
      register: vector_validate_config