#---
#apiVersion: v1
#kind: Pod
#metadata:
#  labels:
#    app: netology-web
#  name: netology-web
#spec:
#  containers:
#  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
#    imagePullPolicy: Always
#    name: es
#    ports:
#    - containerPort: 8080
#      name: esport
#      protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
  name: netology-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deploy-frontend
spec:
  namespace: netology-ns
  replicas: 3
  selector:
    matchLabels:
      app: fucker
  template:
    metadata:
      labels:
        app: fucker
    spec:
      containers:
      - name: simple-fucker-nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netology-frontend-svc
spec:
  selector:
    app: fucker
  ports:
  - port: 7777
    targetPort: 80

