apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume1
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
