clickhouse:
  hosts: 
    clickhouse01: 
     ansible_host:  192.168.122.100
     ansible_user:  root
     ansible_connection: ssh 
    clickhouse02:
     ansible_host:  192.168.122.30
     ansible_user:  root
     ansible_connection: ssh

     
vector:
  hosts:
    vector01:
     ansible_host:  192.168.122.100
     ansible_user:  root
     ansible_connection: ssh 
    vector02:
     ansible_host:  192.168.122.30
     ansible_user:  root
     ansible_connection: ssh

lighthouse:
  hosts:
    lighthouse01:
     ansible_host:  192.168.122.100
     ansible_user:  root
     ansible_connection: ssh
    lighthouse02:
     ansible_host:  192.168.122.30
     ansible_user:  root
     ansible_connection: ssh

