apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytask1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort:  8080
          name: http
        - containerPort: 44333
          name: https
        env:
         - name: HTTP_PORT
           value: "8080"
         - name: HTTP_PORTS
           value: "44344"
