apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tooltask1
  name: tooltask1
spec:
  containers:
  - name: tooltask1
    image: wbitt/network-multitool
    ports:
    - containerPort:  8080
      name: http
    env:
    - name: HTTP_PORT
      value: "8080"

